image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-preview
      visibility: public
tasks:
  - init: >
      pipenv install
      python docs/assets/welcome.py
    command: >
        pipenv run start;
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: true
