"""Migration

Revision ID: 30d4ed2b9a11
Revises: 7a4fdf1b9755
Create Date: 2024-06-06 16:38:30.859912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d4ed2b9a11'
down_revision: Union[str, None] = '7a4fdf1b9755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charaters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cast')
    op.add_column('locations', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('film_id', sa.Integer(), nullable=True))
    op.drop_constraint('locations_planetId_fkey', 'locations', type_='foreignkey')
    op.drop_constraint('locations_filmId_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key(None, 'locations', 'films', ['film_id'], ['id'])
    op.drop_column('locations', 'filmId')
    op.drop_column('locations', 'planetId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('planetId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('filmId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_filmId_fkey', 'locations', 'films', ['filmId'], ['id'])
    op.create_foreign_key('locations_planetId_fkey', 'locations', 'planets', ['planetId'], ['id'])
    op.drop_column('locations', 'film_id')
    op.drop_column('locations', 'planet_id')
    op.create_table('cast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('film', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['film'], ['films.id'], name='cast_film_fkey'),
    sa.ForeignKeyConstraint(['people'], ['people.id'], name='cast_people_fkey'),
    sa.PrimaryKeyConstraint('id', name='cast_pkey')
    )
    op.drop_table('charaters')
    # ### end Alembic commands ###
