"""Migration

Revision ID: 39dfa516f99b
Revises: 30d4ed2b9a11
Create Date: 2024-06-06 18:20:05.422776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dfa516f99b'
down_revision: Union[str, None] = '30d4ed2b9a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'films', ['episode_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'films', type_='unique')
    # ### end Alembic commands ###
