"""Migration

Revision ID: 7def83258c39
Revises: d3c3e2245440
Create Date: 2024-06-05 20:13:24.094067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7def83258c39'
down_revision: Union[str, None] = 'd3c3e2245440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld_id', sa.Integer(), nullable=True))
    op.drop_constraint('people_homeworld_fkey', 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'planets', ['homeworld_id'], ['id'])
    op.drop_column('people', 'homeworld')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_foreign_key('people_homeworld_fkey', 'people', 'planets', ['homeworld'], ['id'])
    op.drop_column('people', 'homeworld_id')
    # ### end Alembic commands ###
