"""Migration

Revision ID: d3c3e2245440
Revises: c3a7c8b3b450
Create Date: 2024-06-05 20:05:54.924991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c3e2245440'
down_revision: Union[str, None] = 'c3a7c8b3b450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('residents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('people', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people'], ['people.id'], name='residents_people_fkey'),
    sa.ForeignKeyConstraint(['planet'], ['planets.id'], name='residents_planet_fkey'),
    sa.PrimaryKeyConstraint('id', name='residents_pkey')
    )
    # ### end Alembic commands ###
